import type { CatalogShoeDef } from "../catalog-types";

export const ADIDAS_CATALOG: CatalogShoeDef[] = [
  {
    id: "adidas-duramo",
    model: "Duramo",
    brand: "Adidas",
    price: 399,
    category: "beginner",
    bestUse: "Primeiro par acessível para caminhada e corrida leve",
  },
  {
    id: "adidas-runfalcon",
    model: "Runfalcon",
    brand: "Adidas",
    price: 449,
    category: "beginner",
    secondaryCategories: ["daily_trainer"],
  },
  {
    id: "adidas-galaxy",
    model: "Galaxy",
    brand: "Adidas",
    price: 429,
    category: "beginner",
  },
  {
    id: "adidas-supernova",
    model: "Supernova",
    brand: "Adidas",
    price: 599,
    category: "daily_trainer",
    purpose: "Daily trainer clássico e versátil da Adidas",
    valuePosition: "custo-beneficio",
  },
  {
    id: "adidas-supernova-rise",
    model: "Supernova Rise",
    brand: "Adidas",
    price: 799,
    category: "daily_trainer",
    secondaryCategories: ["super_trainer"],
    versatilityScore: 5,
    generation: "current",
    valuePosition: "linha-atual",
  },
  {
    id: "adidas-supernova-prima",
    model: "Supernova Prima",
    brand: "Adidas",
    price: 999,
    category: "super_trainer",
    secondaryCategories: ["daily_trainer"],
    generation: "flagship",
    isFlagship: true,
    beginnerFriendly: false,
    idealPace: "4:15–5:15/km",
  },
  {
    id: "adidas-ultraboost-light",
    model: "Ultraboost Light",
    brand: "Adidas",
    price: 899,
    category: "premium_comfort",
    secondaryCategories: ["daily_trainer"],
    generation: "current",
    cushioningLevel: 5,
  },
  {
    id: "adidas-ultraboost-5x",
    model: "Ultraboost 5X",
    brand: "Adidas",
    price: 1099,
    category: "max_cushion",
    secondaryCategories: ["premium_comfort"],
    generation: "current",
    isFlagship: true,
    cushioningLevel: 5,
  },
  {
    id: "adidas-sl2",
    model: "SL2",
    brand: "Adidas",
    price: 649,
    category: "daily_trainer",
    rideFeel: "equilibrado",
  },
  {
    id: "adidas-response-super",
    model: "Response Super",
    brand: "Adidas",
    price: 749,
    category: "daily_trainer",
    secondaryCategories: ["super_trainer"],
    cushioningLevel: 4,
  },
  {
    id: "adidas-adios-8",
    model: "Adizero Adios 8",
    brand: "Adidas",
    price: 899,
    category: "lightweight",
    secondaryCategories: ["speed_trainer", "daily_trainer"],
    generation: "current",
    rideFeel: "firme",
    idealPace: "4:00–5:00/km",
  },
  {
    id: "adidas-evo-sl",
    model: "EVO SL",
    brand: "Adidas",
    price: 999,
    category: "speed_trainer",
    secondaryCategories: ["lightweight"],
    isAggressive: false,
    beginnerFriendly: false,
    rideFeel: "firme",
    generation: "current",
  },
  {
    id: "adidas-solarboost",
    model: "Solarboost",
    brand: "Adidas",
    price: 899,
    category: "stability",
    stabilityLevel: "alta",
    stabilityLevelNum: 5,
  },
  {
    id: "adidas-adistar",
    model: "Adistar",
    brand: "Adidas",
    price: 1099,
    category: "max_cushion",
    secondaryCategories: ["premium_comfort"],
    cushioningLevel: 5,
  },
  {
    id: "adidas-boston-13",
    model: "Adizero Boston 13",
    brand: "Adidas",
    price: 1299,
    category: "speed_trainer",
    isAggressive: true,
    beginnerFriendly: false,
    generation: "current",
    idealPace: "4:00–5:00/km",
  },
  {
    id: "adidas-takumi-sen-10",
    model: "Takumi Sen 10",
    brand: "Adidas",
    price: 1199,
    category: "race_day",
    secondaryCategories: ["speed_trainer", "lightweight"],
    hasPlate: true,
    experienceLevel: ["avancado"],
    idealPace: "3:45–4:30/km",
  },
  {
    id: "adidas-adios-pro-3",
    model: "Adizero Adios Pro 3",
    brand: "Adidas",
    price: 1899,
    category: "race_day",
    generation: "previous",
    valuePosition: "geracao-anterior",
  },
  {
    id: "adidas-adios-pro-4",
    model: "Adizero Adios Pro 4",
    brand: "Adidas",
    price: 2199,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
    valuePosition: "premium",
    experienceLevel: ["avancado", "elite"],
  },
  {
    id: "adidas-adios-pro-evo-1",
    model: "Adizero Adios Pro Evo 1",
    brand: "Adidas",
    price: 3499,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
    experienceLevel: ["elite"],
    idealPace: "3:00–3:45/km",
  },
  {
    id: "adidas-prime-x-2",
    model: "Adizero Prime X 2 Strung",
    brand: "Adidas",
    price: 2499,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
    experienceLevel: ["elite"],
    idealPace: "3:15–4:00/km",
  },
];
