import type { CatalogShoeDef } from "../catalog-types";

export const ASICS_CATALOG: CatalogShoeDef[] = [
  {
    id: "asics-contend",
    model: "Gel-Contend",
    brand: "Asics",
    price: 399,
    category: "beginner",
  },
  {
    id: "asics-excite",
    model: "Gel-Excite",
    brand: "Asics",
    price: 449,
    category: "beginner",
  },
  {
    id: "asics-pulse",
    model: "Gel-Pulse",
    brand: "Asics",
    price: 499,
    category: "beginner",
    secondaryCategories: ["daily_trainer"],
  },
  {
    id: "asics-cumulus-26",
    model: "Gel-Cumulus 26",
    brand: "Asics",
    price: 899,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "current",
    rideFeel: "macio",
  },
  {
    id: "asics-novablast-4",
    model: "Novablast 4",
    brand: "Asics",
    price: 999,
    category: "super_trainer",
    secondaryCategories: ["daily_trainer"],
    beginnerFriendly: false,
    rideFeel: "firme",
    generation: "current",
  },
  {
    id: "asics-kayano-31",
    model: "Gel-Kayano 31",
    brand: "Asics",
    price: 1199,
    category: "stability",
    stabilityLevel: "alta",
    stabilityLevelNum: 5,
    generation: "current",
    isFlagship: true,
  },
  {
    id: "asics-nimbus-26",
    model: "Gel-Nimbus 26",
    brand: "Asics",
    price: 1299,
    category: "premium_comfort",
    secondaryCategories: ["max_cushion"],
    cushioningLevel: 5,
    generation: "current",
    isFlagship: true,
  },
  {
    id: "asics-gt-2000",
    model: "GT-2000",
    brand: "Asics",
    price: 849,
    category: "stability",
    secondaryCategories: ["daily_trainer"],
    stabilityLevel: "alta",
    valuePosition: "custo-beneficio",
  },
  {
    id: "asics-glideride-max",
    model: "Glideride Max",
    brand: "Asics",
    price: 1099,
    category: "max_cushion",
    secondaryCategories: ["recovery"],
    cushioningLevel: 5,
    idealPace: "5:30/km ou mais lento",
  },
  {
    id: "asics-magic-speed-4",
    model: "Magic Speed 4",
    brand: "Asics",
    price: 1099,
    category: "speed_trainer",
    hasPlate: true,
    generation: "current",
  },
  {
    id: "asics-superblast-2",
    model: "Superblast 2",
    brand: "Asics",
    price: 1399,
    category: "super_trainer",
    secondaryCategories: ["speed_trainer"],
    generation: "previous",
    valuePosition: "geracao-anterior",
    idealPace: "4:00–5:00/km",
  },
  {
    id: "asics-superblast-3",
    model: "Superblast 3",
    brand: "Asics",
    price: 1599,
    category: "super_trainer",
    secondaryCategories: ["speed_trainer"],
    generation: "flagship",
    isFlagship: true,
    idealPace: "3:50–5:00/km",
  },
  {
    id: "asics-metaspeed-sky",
    model: "Metaspeed Sky Paris",
    brand: "Asics",
    price: 1899,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
    idealPace: "3:30–4:30/km (passada longa)",
  },
  {
    id: "asics-metaspeed-edge",
    model: "Metaspeed Edge Paris",
    brand: "Asics",
    price: 1899,
    category: "race_day",
    secondaryCategories: ["speed_trainer"],
    hasPlate: true,
    generation: "flagship",
    isFlagship: true,
    idealPace: "3:20–4:15/km (passada curta)",
  },
];
