import type { CatalogShoeDef } from "../catalog-types";

export const HOKA_CATALOG: CatalogShoeDef[] = [
  {
    id: "hoka-rincon-4",
    model: "Rincon 4",
    brand: "Hoka",
    price: 799,
    category: "lightweight",
    secondaryCategories: ["daily_trainer"],
    rideFeel: "equilibrado",
    valuePosition: "custo-beneficio",
  },
  {
    id: "hoka-clifton-9",
    model: "Clifton 9",
    brand: "Hoka",
    price: 799,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "previous",
    valuePosition: "geracao-anterior",
    rideFeel: "macio",
  },
  {
    id: "hoka-clifton-10",
    model: "Clifton 10",
    brand: "Hoka",
    price: 899,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "current",
    isFlagship: true,
    rideFeel: "macio",
  },
  {
    id: "hoka-arahi-7",
    model: "Arahi 7",
    brand: "Hoka",
    price: 1099,
    category: "stability",
    stabilityLevel: "alta",
    stabilityLevelNum: 5,
    generation: "current",
  },
  {
    id: "hoka-gaviota-5",
    model: "Gaviota 5",
    brand: "Hoka",
    price: 1199,
    category: "stability",
    secondaryCategories: ["max_cushion"],
    stabilityLevel: "alta",
    stabilityLevelNum: 5,
    idealWeight: ["90-100", "100-110", "acima-110"],
  },
  {
    id: "hoka-bondi-9",
    model: "Bondi 9",
    brand: "Hoka",
    price: 1199,
    category: "max_cushion",
    secondaryCategories: ["recovery", "premium_comfort"],
    cushioningLevel: 5,
    generation: "current",
    isFlagship: true,
  },
  {
    id: "hoka-challenger-8",
    model: "Challenger 8",
    brand: "Hoka",
    price: 999,
    category: "daily_trainer",
    bestUse: "Treino diário versátil com tração para trilha leve",
    secondaryCategories: ["lightweight"],
  },
  {
    id: "hoka-mach-6",
    model: "Mach 6",
    brand: "Hoka",
    price: 1099,
    category: "speed_trainer",
    secondaryCategories: ["super_trainer"],
    generation: "previous",
    valuePosition: "geracao-anterior",
    rideFeel: "firme",
  },
  {
    id: "hoka-mach-x-2",
    model: "Mach X 2",
    brand: "Hoka",
    price: 1299,
    category: "super_trainer",
    secondaryCategories: ["speed_trainer"],
    generation: "current",
    hasPlate: true,
    rideFeel: "firme",
  },
  {
    id: "hoka-skyward-x",
    model: "Skyward X",
    brand: "Hoka",
    price: 1499,
    category: "super_trainer",
    secondaryCategories: ["max_cushion"],
    generation: "flagship",
    isFlagship: true,
    cushioningLevel: 5,
  },
  {
    id: "hoka-cielo-x1",
    model: "Cielo X1",
    brand: "Hoka",
    price: 2199,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
    experienceLevel: ["elite"],
  },
  {
    id: "hoka-rocket-x-2",
    model: "Rocket X 2",
    brand: "Hoka",
    price: 1799,
    category: "race_day",
    generation: "current",
    isFlagship: true,
    valuePosition: "linha-atual",
  },
];
