import type { CatalogShoeDef } from "../catalog-types";

export const MIZUNO_CATALOG: CatalogShoeDef[] = [
  {
    id: "mizuno-maximizer",
    model: "Wave Maximizer",
    brand: "Mizuno",
    price: 449,
    category: "beginner",
  },
  {
    id: "mizuno-sonic",
    model: "Wave Sonic",
    brand: "Mizuno",
    price: 499,
    category: "beginner",
    secondaryCategories: ["daily_trainer"],
  },
  {
    id: "mizuno-rider-27",
    model: "Wave Rider 27",
    brand: "Mizuno",
    price: 899,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "previous",
    valuePosition: "geracao-anterior",
    rideFeel: "equilibrado",
  },
  {
    id: "mizuno-rider-28",
    model: "Wave Rider 28",
    brand: "Mizuno",
    price: 999,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "current",
    isFlagship: true,
    rideFeel: "equilibrado",
  },
  {
    id: "mizuno-inspire",
    model: "Wave Inspire",
    brand: "Mizuno",
    price: 949,
    category: "stability",
    stabilityLevel: "alta",
    valuePosition: "custo-beneficio",
  },
  {
    id: "mizuno-horizon-7",
    model: "Wave Horizon 7",
    brand: "Mizuno",
    price: 1049,
    category: "stability",
    secondaryCategories: ["max_cushion"],
    stabilityLevel: "alta",
    stabilityLevelNum: 5,
  },
  {
    id: "mizuno-sky-7",
    model: "Wave Sky 8",
    brand: "Mizuno",
    price: 1099,
    category: "premium_comfort",
    secondaryCategories: ["max_cushion"],
    cushioningLevel: 5,
    generation: "current",
    isFlagship: true,
  },
  {
    id: "mizuno-paradox",
    model: "Wave Paradox",
    brand: "Mizuno",
    price: 899,
    category: "stability",
    stabilityLevel: "alta",
    idealWeight: ["80-90", "90-100", "100-110", "acima-110"],
  },
  {
    id: "mizuno-neo-wind",
    model: "Wave Neo Wind",
    brand: "Mizuno",
    price: 1199,
    category: "super_trainer",
    secondaryCategories: ["daily_trainer"],
    generation: "current",
  },
  {
    id: "mizuno-rebellion-flash",
    model: "Wave Rebellion Flash",
    brand: "Mizuno",
    price: 1199,
    category: "speed_trainer",
    secondaryCategories: ["lightweight"],
    generation: "current",
  },
  {
    id: "mizuno-wave-duel",
    model: "Wave Duel",
    brand: "Mizuno",
    price: 999,
    category: "lightweight",
    isAggressive: true,
    idealPace: "4:00–5:00/km",
  },
  {
    id: "mizuno-rebellion-pro",
    model: "Wave Rebellion Pro",
    brand: "Mizuno",
    price: 1399,
    category: "race_day",
    hasPlate: true,
    generation: "current",
    isFlagship: true,
  },
  {
    id: "mizuno-neo-vista",
    model: "Neo Vista",
    brand: "Mizuno",
    price: 1799,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
    valuePosition: "linha-atual",
  },
];
