import type { CatalogShoeDef } from "../catalog-types";

export const NEW_BALANCE_CATALOG: CatalogShoeDef[] = [
  {
    id: "nb-kairos",
    model: "Fresh Foam X Kairos",
    brand: "New Balance",
    price: 449,
    category: "beginner",
    valuePosition: "economico",
  },
  {
    id: "nb-880v14",
    model: "Fresh Foam X 880v14",
    brand: "New Balance",
    price: 899,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "current",
    rideFeel: "equilibrado",
  },
  {
    id: "nb-860v14",
    model: "Fresh Foam X 860v14",
    brand: "New Balance",
    price: 949,
    category: "stability",
    stabilityLevel: "alta",
    stabilityLevelNum: 5,
    generation: "current",
  },
  {
    id: "nb-1080v14",
    model: "Fresh Foam X 1080v14",
    brand: "New Balance",
    price: 1099,
    category: "premium_comfort",
    secondaryCategories: ["max_cushion"],
    cushioningLevel: 5,
    generation: "current",
    isFlagship: true,
  },
  {
    id: "nb-more-v5",
    model: "Fresh Foam X More v5",
    brand: "New Balance",
    price: 1199,
    category: "max_cushion",
    secondaryCategories: ["recovery"],
    cushioningLevel: 5,
    idealWeight: ["80-90", "90-100", "100-110", "acima-110"],
  },
  {
    id: "nb-rebel-v4",
    model: "FuelCell Rebel v4",
    brand: "New Balance",
    price: 1099,
    category: "super_trainer",
    secondaryCategories: ["daily_trainer"],
    generation: "current",
    isFlagship: true,
    rideFeel: "firme",
  },
  {
    id: "nb-rebel-v3",
    model: "FuelCell Rebel v3",
    brand: "New Balance",
    price: 799,
    category: "super_trainer",
    generation: "previous",
    valuePosition: "geracao-anterior",
  },
  {
    id: "nb-sc-trainer-v3",
    model: "FuelCell SC Trainer v3",
    brand: "New Balance",
    price: 1399,
    category: "super_trainer",
    secondaryCategories: ["speed_trainer"],
    hasPlate: true,
    generation: "current",
    experienceLevel: ["intermediario", "avancado"],
  },
  {
    id: "nb-propel-v5",
    model: "FuelCell Propel v5",
    brand: "New Balance",
    price: 799,
    category: "speed_trainer",
    secondaryCategories: ["lightweight"],
    valuePosition: "custo-beneficio",
  },
  {
    id: "nb-sc-elite-v4",
    model: "FuelCell SuperComp Elite v4",
    brand: "New Balance",
    price: 1999,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
  },
  {
    id: "nb-sc-pacer",
    model: "FuelCell SuperComp Pacer",
    brand: "New Balance",
    price: 1399,
    category: "race_day",
    secondaryCategories: ["speed_trainer"],
    hasPlate: true,
    experienceLevel: ["intermediario", "avancado"],
    generation: "current",
  },
];
