import type { CatalogShoeDef } from "../catalog-types";

export const NIKE_CATALOG: CatalogShoeDef[] = [
  {
    id: "nike-downshifter",
    model: "Downshifter",
    brand: "Nike",
    price: 379,
    category: "beginner",
  },
  {
    id: "nike-winflo",
    model: "Winflo",
    brand: "Nike",
    price: 449,
    category: "beginner",
    secondaryCategories: ["daily_trainer"],
  },
  {
    id: "nike-revolution",
    model: "Revolution",
    brand: "Nike",
    price: 399,
    category: "beginner",
  },
  {
    id: "nike-pegasus-41",
    model: "Pegasus 41",
    brand: "Nike",
    price: 899,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "current",
    valuePosition: "linha-atual",
  },
  {
    id: "nike-quest",
    model: "Quest",
    brand: "Nike",
    price: 549,
    category: "daily_trainer",
    valuePosition: "custo-beneficio",
  },
  {
    id: "nike-structure-25",
    model: "Structure 25",
    brand: "Nike",
    price: 899,
    category: "stability",
    stabilityLevel: "alta",
    stabilityLevelNum: 5,
  },
  {
    id: "nike-vomero-17",
    model: "Vomero 17",
    brand: "Nike",
    price: 949,
    category: "premium_comfort",
    secondaryCategories: ["max_cushion"],
    generation: "previous",
    valuePosition: "geracao-anterior",
    cushioningLevel: 5,
  },
  {
    id: "nike-vomero-18",
    model: "Vomero 18",
    brand: "Nike",
    price: 1099,
    category: "premium_comfort",
    secondaryCategories: ["max_cushion"],
    cushioningLevel: 5,
    generation: "current",
    isFlagship: true,
  },
  {
    id: "nike-invincible-3",
    model: "Invincible 3",
    brand: "Nike",
    price: 1299,
    category: "recovery",
    secondaryCategories: ["max_cushion"],
    versatilityScore: 3,
    idealPace: "5:30/km ou mais lento",
  },
  {
    id: "nike-pegasus-premium",
    model: "Pegasus Premium",
    brand: "Nike",
    price: 999,
    category: "super_trainer",
    secondaryCategories: ["daily_trainer"],
    generation: "current",
    isFlagship: true,
  },
  {
    id: "nike-streakfly",
    model: "Streakfly",
    brand: "Nike",
    price: 999,
    category: "lightweight",
    secondaryCategories: ["speed_trainer"],
    isAggressive: true,
    idealPace: "3:50–4:45/km",
  },
  {
    id: "nike-zoom-fly-6",
    model: "Zoom Fly 6",
    brand: "Nike",
    price: 1299,
    category: "race_day",
    secondaryCategories: ["speed_trainer"],
    hasPlate: true,
    generation: "current",
    valuePosition: "linha-atual",
    experienceLevel: ["intermediario", "avancado"],
  },
  {
    id: "nike-vaporfly-3",
    model: "Vaporfly 3",
    brand: "Nike",
    price: 1999,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
  },
  {
    id: "nike-alphafly-3",
    model: "Alphafly 3",
    brand: "Nike",
    price: 2799,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
    experienceLevel: ["elite"],
  },
];
