import type { CatalogShoeDef } from "../catalog-types";

export const OLYMPIKUS_CATALOG: CatalogShoeDef[] = [
  {
    id: "olympikus-active",
    model: "Active",
    brand: "Olympikus",
    price: 399,
    category: "beginner",
    valuePosition: "economico",
  },
  {
    id: "olympikus-corre-4",
    model: "Corre 4",
    brand: "Olympikus",
    price: 499,
    category: "beginner",
    secondaryCategories: ["daily_trainer"],
  },
  {
    id: "olympikus-fleeting-2",
    model: "Fleeting 2",
    brand: "Olympikus",
    price: 549,
    category: "beginner",
  },
  {
    id: "olympikus-streak",
    model: "Streak",
    brand: "Olympikus",
    price: 549,
    category: "daily_trainer",
    valuePosition: "custo-beneficio",
  },
  {
    id: "olympikus-corre-max",
    model: "Corre Max",
    brand: "Olympikus",
    price: 599,
    category: "max_cushion",
    secondaryCategories: ["beginner"],
    cushioningLevel: 4,
  },
  {
    id: "olympikus-corre-trilha",
    model: "Corre Trilha",
    brand: "Olympikus",
    price: 649,
    category: "daily_trainer",
    bestUse: "Treino diário com versatilidade para trilha leve",
  },
  {
    id: "olympikus-dexter-3",
    model: "Dexter 3",
    brand: "Olympikus",
    price: 749,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "current",
  },
  {
    id: "olympikus-corre-veloz",
    model: "Corre Veloz",
    brand: "Olympikus",
    price: 699,
    category: "lightweight",
    secondaryCategories: ["speed_trainer"],
  },
  {
    id: "olympikus-corre-gt",
    model: "Corre GT",
    brand: "Olympikus",
    price: 799,
    category: "speed_trainer",
    beginnerFriendly: false,
    generation: "current",
  },
  {
    id: "olympikus-corre-supra",
    model: "Corre Supra",
    brand: "Olympikus",
    price: 899,
    category: "super_trainer",
    secondaryCategories: ["daily_trainer"],
    generation: "current",
  },
  {
    id: "olympikus-corre-grafeno-3",
    model: "Corre Grafeno 3",
    brand: "Olympikus",
    price: 999,
    category: "race_day",
    hasPlate: true,
    experienceLevel: ["intermediario", "avancado"],
    valuePosition: "linha-atual",
  },
];
