import type { CatalogShoeDef } from "../catalog-types";

export const PUMA_CATALOG: CatalogShoeDef[] = [
  {
    id: "puma-aviate",
    model: "Aviate",
    brand: "Puma",
    price: 399,
    category: "beginner",
  },
  {
    id: "puma-scend",
    model: "Scend Pro",
    brand: "Puma",
    price: 449,
    category: "beginner",
  },
  {
    id: "puma-everspeed",
    model: "Everspeed",
    brand: "Puma",
    price: 479,
    category: "beginner",
    secondaryCategories: ["daily_trainer"],
    valuePosition: "economico",
  },
  {
    id: "puma-foreverrun",
    model: "ForeverRun Nitro",
    brand: "Puma",
    price: 699,
    category: "daily_trainer",
    valuePosition: "custo-beneficio",
  },
  {
    id: "puma-velocity-3",
    model: "Velocity Nitro 3",
    brand: "Puma",
    price: 799,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "current",
  },
  {
    id: "puma-foreverrun-plus",
    model: "ForeverRun Nitro 2",
    brand: "Puma",
    price: 899,
    category: "super_trainer",
    secondaryCategories: ["daily_trainer"],
    generation: "current",
  },
  {
    id: "puma-liberate",
    model: "Liberate Nitro",
    brand: "Puma",
    price: 849,
    category: "lightweight",
    secondaryCategories: ["speed_trainer"],
    rideFeel: "agressivo",
  },
  {
    id: "puma-magnify-2",
    model: "Magnify Nitro 2",
    brand: "Puma",
    price: 999,
    category: "max_cushion",
    secondaryCategories: ["recovery"],
    cushioningLevel: 5,
  },
  {
    id: "puma-magmax-nitro",
    model: "MagMax Nitro",
    brand: "Puma",
    price: 1199,
    category: "max_cushion",
    secondaryCategories: ["premium_comfort"],
    generation: "flagship",
    isFlagship: true,
    cushioningLevel: 5,
  },
  {
    id: "puma-deviate-2",
    model: "Deviate Nitro 2",
    brand: "Puma",
    price: 999,
    category: "speed_trainer",
    hasPlate: true,
    generation: "previous",
    valuePosition: "geracao-anterior",
  },
  {
    id: "puma-deviate-3",
    model: "Deviate Nitro 3",
    brand: "Puma",
    price: 1299,
    category: "speed_trainer",
    hasPlate: true,
    generation: "current",
  },
  {
    id: "puma-fast-r",
    model: "Fast-R Nitro",
    brand: "Puma",
    price: 1299,
    category: "race_day",
    hasPlate: true,
    generation: "previous",
    valuePosition: "geracao-anterior",
  },
  {
    id: "puma-fast-r-elite-2",
    model: "Fast-R Nitro Elite 2",
    brand: "Puma",
    price: 1699,
    category: "race_day",
    hasPlate: true,
    generation: "current",
    isFlagship: true,
  },
  {
    id: "puma-deviate-elite",
    model: "Deviate Nitro Elite",
    brand: "Puma",
    price: 1599,
    category: "race_day",
    generation: "previous",
    valuePosition: "geracao-anterior",
  },
  {
    id: "puma-deviate-elite-3",
    model: "Deviate Nitro Elite 3",
    brand: "Puma",
    price: 1999,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
    experienceLevel: ["avancado", "elite"],
  },
];
