import type { CatalogShoeDef } from "../catalog-types";

export const SAUCONY_CATALOG: CatalogShoeDef[] = [
  {
    id: "saucony-cohesion",
    model: "Cohesion",
    brand: "Saucony",
    price: 399,
    category: "beginner",
    valuePosition: "economico",
  },
  {
    id: "saucony-ride-17",
    model: "Ride 17",
    brand: "Saucony",
    price: 899,
    category: "daily_trainer",
    versatilityScore: 5,
    generation: "current",
  },
  {
    id: "saucony-guide-17",
    model: "Guide 17",
    brand: "Saucony",
    price: 949,
    category: "stability",
    stabilityLevel: "alta",
    valuePosition: "custo-beneficio",
  },
  {
    id: "saucony-tempus",
    model: "Tempus",
    brand: "Saucony",
    price: 1199,
    category: "stability",
    secondaryCategories: ["super_trainer"],
    stabilityLevel: "alta",
    stabilityLevelNum: 5,
    generation: "current",
  },
  {
    id: "saucony-triumph-22",
    model: "Triumph 22",
    brand: "Saucony",
    price: 1199,
    category: "premium_comfort",
    secondaryCategories: ["max_cushion", "recovery"],
    cushioningLevel: 5,
    generation: "current",
    isFlagship: true,
  },
  {
    id: "saucony-hurricane-24",
    model: "Hurricane 24",
    brand: "Saucony",
    price: 1299,
    category: "max_cushion",
    secondaryCategories: ["stability"],
    cushioningLevel: 5,
    stabilityLevelNum: 4,
  },
  {
    id: "saucony-kinvara-15",
    model: "Kinvara 15",
    brand: "Saucony",
    price: 899,
    category: "lightweight",
    secondaryCategories: ["daily_trainer"],
    rideFeel: "agressivo",
    idealPace: "4:15–5:15/km",
  },
  {
    id: "saucony-kinvara-pro",
    model: "Kinvara Pro",
    brand: "Saucony",
    price: 1199,
    category: "super_trainer",
    secondaryCategories: ["lightweight", "speed_trainer"],
    generation: "flagship",
    isFlagship: true,
    rideFeel: "firme",
  },
  {
    id: "saucony-axon-3",
    model: "Axon 3",
    brand: "Saucony",
    price: 1099,
    category: "super_trainer",
    secondaryCategories: ["speed_trainer"],
    generation: "current",
  },
  {
    id: "saucony-endorphin-speed-4",
    model: "Endorphin Speed 4",
    brand: "Saucony",
    price: 1299,
    category: "speed_trainer",
    hasPlate: true,
    generation: "current",
    valuePosition: "linha-atual",
  },
  {
    id: "saucony-endorphin-pro-4",
    model: "Endorphin Pro 4",
    brand: "Saucony",
    price: 1899,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
  },
  {
    id: "saucony-endorphin-elite",
    model: "Endorphin Elite",
    brand: "Saucony",
    price: 2299,
    category: "race_day",
    generation: "flagship",
    isFlagship: true,
    experienceLevel: ["elite"],
    idealPace: "3:10–4:00/km",
  },
];
