import type { TechnicalSpecOverride } from "./catalog-technical";

/** Specs detalhados — modelos premium, flagship e elite marathon */
export const PREMIUM_TECH_OVERRIDES: Record<string, TechnicalSpecOverride> = {
  "adidas-adios-pro-evo-1": {
    foamMidsole: "lightstrike_pro",
    foamSecondary: "peba",
    hasPlate: true,
    plateType: "energy_rod",
    weightGrams: 185,
    aggressiveness: "race_day_extremo",
    stackHeelMm: 39,
    stackForefootMm: 33,
    dropMm: 6,
    rocker: "meta_rocker",
    stability: 2,
    softness: 3,
    responsiveness: 5,
    durability: 1,
    energyReturn: 5,
    adaptationLevel: "elite",
    isFlagship: true,
    volumeHandling: "race_only",
    idealUses: ["maratona", "meia_maratona", "prova_curta"],
    idealRunnerLevel: ["elite"],
    rideDescription:
      "Flagship absoluto da Adidas — Lightstrike Pro ultraleve com eficiência energética máxima para maratona de elite.",
    gaitDescription:
      "Passada de elite com rocker agressivo — favorece corredores com biomecânica eficiente e cadência alta.",
    volumeNotes: "Exclusivo para prova e simulações de ritmo — desgaste extremamente rápido no uso diário.",
    modelDifferentiator:
      "O tênis mais avançado da Adidas — mais extremo que Adios Pro 4, pensado para recordes e provas olímpicas.",
    realStrengths: ["Eficiência energética máxima", "Peso mínimo", "Tecnologia de ponta"],
    realLimitations: ["Preço extremo", "Adaptação elite obrigatória", "Zero versatilidade para treino"],
  },
  "adidas-adios-pro-4": {
    foamMidsole: "lightstrike_pro",
    hasPlate: true,
    plateType: "energy_rod",
    weightGrams: 210,
    aggressiveness: "race_day_extremo",
    stackHeelMm: 40,
    dropMm: 6,
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["maratona", "meia_maratona"],
    modelDifferentiator:
      "Flagship de maratona Adidas — evolução do Pro 3 com mais estabilidade em alta velocidade que o Evo 1 extremo.",
    realStrengths: ["Economia de corrida comprovada", "Placa EnergyRods refinada", "Versátil para maratona e meia"],
  },
  "adidas-prime-x-2": {
    foamMidsole: "lightstrike_pro",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 220,
    stackHeelMm: 50,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "elite",
    isFlagship: true,
    modelDifferentiator:
      "Stack altíssimo com tecnologia Strung — plataforma experimental para máxima amortecimento em prova longa.",
    realLimitations: ["Instável para corredores sem técnica", "Proibido em algumas provas por stack"],
  },
  "adidas-supernova-prima": {
    foamMidsole: "lightstrike_pro",
    weightGrams: 265,
    aggressiveness: "responsivo",
    responsiveness: 4,
    energyReturn: 4,
    adaptationLevel: "moderada",
    isFlagship: true,
    idealUses: ["rodagem_diaria", "treino_ritmo", "longao"],
    modelDifferentiator:
      "Super trainer flagship Adidas — mais resposta que Rise, sem exigir nível de placa de prova.",
  },
  "adidas-ultraboost-light": {
    foamMidsole: "lightstrike",
    weightGrams: 275,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["rodagem_diaria", "regenerativo"],
    modelDifferentiator: "Premium conforto lifestyle-running — macio e acessível, oposto ao Adizero performance.",
  },
  "adidas-ultraboost-5x": {
    foamMidsole: "lightstrike",
    weightGrams: 295,
    stackHeelMm: 42,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    isFlagship: true,
    idealUses: ["longao", "regenerativo", "rodagem_diaria"],
    modelDifferentiator: "Max cushion premium Adidas — stack alto para conforto máximo, não para ritmo.",
  },
  "adidas-adios-8": {
    foamMidsole: "lightstrike_pro",
    weightGrams: 245,
    aggressiveness: "responsivo",
    responsiveness: 4,
    energyReturn: 4,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "intervalado", "rodagem_diaria"],
    modelDifferentiator:
      "Daily rápido da linha Adizero — mais acessível que Boston, sem placa, ideal para turnover.",
  },
  "asics-superblast-3": {
    foamMidsole: "ff_turbo_plus",
    weightGrams: 250,
    stackHeelMm: 42,
    aggressiveness: "responsivo",
    responsiveness: 5,
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["treino_ritmo", "intervalado", "rodagem_diaria"],
    modelDifferentiator:
      "Flagship super trainer Asics — FF Turbo+ mais refinado que Superblast 2, rebote máximo sem placa.",
    realStrengths: ["Rebote premium", "Versátil para treinos exigentes", "Tecnologia FF Turbo+ atualizada"],
    realLimitations: ["Instável para corredores pesados", "Exige adaptação ao rebote elástico"],
  },
  "asics-superblast-2": {
    foamMidsole: "ff_turbo_plus",
    weightGrams: 255,
    aggressiveness: "responsivo",
    responsiveness: 5,
    energyReturn: 5,
    adaptationLevel: "alta",
    idealUses: ["treino_ritmo", "intervalado", "rodagem_diaria"],
    modelDifferentiator:
      "Geração anterior do Superblast — excelente custo-benefício com FF Turbo+ quando o budget não alcança a v3.",
  },
  "asics-metaspeed-sky": {
    foamMidsole: "ff_turbo",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 215,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["maratona"],
    modelDifferentiator:
      "Super shoe Paris para passada longa — curva otimizada para maratonistas com cadência mais baixa.",
  },
  "asics-metaspeed-edge": {
    foamMidsole: "ff_turbo",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 210,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["meia_maratona", "prova_curta"],
    modelDifferentiator:
      "Super shoe Paris para passada curta — mais ágil que Sky, ideal para 5K–21K com cadência alta.",
  },
  "nike-alphafly-3": {
    foamMidsole: "zoomx",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 220,
    stackHeelMm: 40,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "elite",
    isFlagship: true,
    idealUses: ["maratona"],
    modelDifferentiator:
      "Flagship Nike com Air Pods + ZoomX — máximo amortecimento entre super shoes, feito para maratona longa.",
    realStrengths: ["Eficiência energética comprovada", "Amortecimento premium em prova", "Estabilidade em alta velocidade"],
    realLimitations: ["Exige técnica avançada", "Não serve para treino diário", "Preço flagship"],
  },
  "nike-vaporfly-3": {
    foamMidsole: "zoomx",
    hasPlate: true,
    weightGrams: 210,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["meia_maratona", "maratona", "prova_curta"],
    modelDifferentiator:
      "Referência de super shoe — mais ágil que Alphafly, versátil de 10K a maratona.",
  },
  "nike-pegasus-premium": {
    foamMidsole: "zoomx",
    weightGrams: 268,
    aggressiveness: "responsivo",
    responsiveness: 4,
    energyReturn: 4,
    adaptationLevel: "moderada",
    isFlagship: true,
    idealUses: ["rodagem_diaria", "treino_ritmo", "longao"],
    modelDifferentiator:
      "Super trainer Nike flagship — ZoomX no daily sem ser super shoe de prova.",
  },
  "nike-vomero-17": {
    foamMidsole: "zoomx",
    weightGrams: 285,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["rodagem_diaria", "longao", "regenerativo"],
    modelDifferentiator:
      "Geração anterior do Vomero — conforto ZoomX premium com excelente custo-benefício vs Vomero 18.",
  },
  "nb-sc-elite-v4": {
    foamMidsole: "fuelcell",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 215,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["maratona", "meia_maratona"],
    modelDifferentiator: "Flagship NB de prova — FuelCell PEBA com placa de carbono para elite marathon.",
  },
  "nb-sc-trainer-v3": {
    foamMidsole: "fuelcell",
    hasPlate: true,
    plateType: "composite",
    weightGrams: 255,
    aggressiveness: "responsivo",
    energyReturn: 4,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "intervalado", "meia_maratona"],
    modelDifferentiator:
      "Super trainer com placa — treine com tecnologia de prova sem preço de SC Elite.",
  },
  "nb-rebel-v4": {
    foamMidsole: "fuelcell",
    weightGrams: 262,
    aggressiveness: "responsivo",
    energyReturn: 4,
    adaptationLevel: "moderada",
    isFlagship: true,
    idealUses: ["rodagem_diaria", "treino_ritmo", "intervalado"],
    modelDifferentiator: "Super trainer flagship NB — rebote FuelCell para daily exigente.",
  },
  "saucony-endorphin-elite": {
    foamMidsole: "pwrrun_pb",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 210,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "elite",
    isFlagship: true,
    idealUses: ["maratona", "meia_maratona", "prova_curta"],
    modelDifferentiator:
      "Topo absoluto Saucony — acima do Pro 4, PWRRUN PB máximo para corredores de elite.",
  },
  "saucony-endorphin-pro-4": {
    foamMidsole: "pwrrun_pb",
    hasPlate: true,
    weightGrams: 215,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["maratona", "meia_maratona"],
    modelDifferentiator: "Flagship de prova Saucony — mais acessível que Elite, referência em super shoe.",
  },
  "saucony-kinvara-pro": {
    foamMidsole: "pwrrun_pb",
    weightGrams: 250,
    aggressiveness: "responsivo",
    energyReturn: 4,
    adaptationLevel: "moderada",
    isFlagship: true,
    idealUses: ["treino_ritmo", "intervalado", "rodagem_diaria"],
    modelDifferentiator:
      "Super trainer leve Saucony — PWRRUN PB no daily rápido, evolução do Kinvara clássico.",
  },
  "hoka-cielo-x1": {
    foamMidsole: "peba",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 210,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "elite",
    isFlagship: true,
    idealUses: ["maratona", "meia_maratona"],
    modelDifferentiator: "Flagship Hoka de prova — PEBA + placa para máxima eficiência energética.",
  },
  "hoka-skyward-x": {
    foamMidsole: "peba",
    weightGrams: 280,
    stackHeelMm: 45,
    aggressiveness: "responsivo",
    energyReturn: 4,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["longao", "treino_ritmo", "rodagem_diaria"],
    modelDifferentiator:
      "Super trainer max stack Hoka — amortecimento premium com resposta, oposto ao Bondi conforto puro.",
  },
  "hoka-mach-x-2": {
    foamMidsole: "peba",
    hasPlate: true,
    plateType: "composite",
    weightGrams: 265,
    aggressiveness: "responsivo",
    energyReturn: 4,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "intervalado"],
    modelDifferentiator: "Super trainer com placa Hoka — ritmo e intervalado com tecnologia de prova.",
  },
  "hoka-clifton-10": {
    foamMidsole: "cmeva",
    weightGrams: 265,
    aggressiveness: "confortavel",
    softness: 4,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    isFlagship: true,
    idealUses: ["rodagem_diaria", "longao"],
    modelDifferentiator: "Daily flagship Hoka — meta-rocker refinado, referência de easy running.",
  },
  "puma-deviate-elite-3": {
    foamMidsole: "nitro_elite",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 215,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["maratona", "meia_maratona"],
    modelDifferentiator: "Flagship Puma de prova — Nitro Elite máximo com placa de carbono.",
  },
  "puma-deviate-3": {
    foamMidsole: "nitro",
    hasPlate: true,
    plateType: "composite",
    weightGrams: 255,
    aggressiveness: "agressivo",
    energyReturn: 4,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "intervalado", "meia_maratona"],
    modelDifferentiator: "Speed trainer atual Puma — placa acessível para treinos de qualidade.",
  },
  "puma-fast-r-elite-2": {
    foamMidsole: "nitro_elite",
    hasPlate: true,
    weightGrams: 220,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["prova_curta", "meia_maratona", "maratona"],
    modelDifferentiator: "Super shoe Puma — Nitro Elite para prova, acima do Deviate Nitro 3.",
  },
  "puma-magmax-nitro": {
    foamMidsole: "nitro",
    weightGrams: 305,
    stackHeelMm: 44,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    isFlagship: true,
    idealUses: ["longao", "regenerativo", "rodagem_diaria"],
    modelDifferentiator: "Max cushion flagship Puma — Nitro generoso para proteção máxima.",
  },
  "mizuno-neo-vista": {
    foamMidsole: "enerzy_nxt",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 225,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["maratona", "meia_maratona"],
    modelDifferentiator: "Flagship Mizuno de prova — Enerzy Nxt responsivo com placa de carbono.",
  },
  "mizuno-rebellion-pro": {
    foamMidsole: "enerzy_nxt",
    hasPlate: true,
    weightGrams: 230,
    aggressiveness: "agressivo",
    energyReturn: 4,
    adaptationLevel: "alta",
    isFlagship: true,
    idealUses: ["meia_maratona", "prova_curta", "treino_ritmo"],
    modelDifferentiator: "Race day Mizuno — placa e Enerzy Nxt para ritmo forte, abaixo do Neo Vista.",
  },
  "mizuno-rider-28": {
    foamMidsole: "enerzy",
    weightGrams: 275,
    aggressiveness: "equilibrado",
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    isFlagship: true,
    idealUses: ["rodagem_diaria", "longao"],
    modelDifferentiator: "Daily flagship Mizuno — Wave + Enerzy equilibrado, geração atual.",
  },
  "mizuno-sky-7": {
    foamMidsole: "enerzy",
    weightGrams: 290,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    isFlagship: true,
    idealUses: ["rodagem_diaria", "longao", "regenerativo"],
    modelDifferentiator: "Premium comfort Mizuno — máximo amortecimento Wave Sky para easy days.",
  },
  "adidas-boston-13": {
    foamMidsole: "lightstrike_pro",
    weightGrams: 255,
    aggressiveness: "responsivo",
    responsiveness: 4,
    energyReturn: 4,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "intervalado", "rodagem_diaria"],
    modelDifferentiator: "Super trainer com Lightstrike Pro — ritmo e longão sem placa de prova.",
  },
  "adidas-supernova-rise": {
    foamMidsole: "lightstrike",
    weightGrams: 285,
    aggressiveness: "equilibrado",
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["rodagem_diaria", "longao"],
    modelDifferentiator: "Daily versátil Adidas — conforto e durabilidade para volume semanal.",
  },
  "asics-novablast-4": {
    foamMidsole: "ff_blast_plus",
    weightGrams: 260,
    aggressiveness: "responsivo",
    responsiveness: 4,
    energyReturn: 4,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "intervalado", "rodagem_diaria"],
    modelDifferentiator: "Daily responsivo Asics — rebote FF Blast+ para treinos dinâmicos.",
  },
  "asics-nimbus-26": {
    foamMidsole: "ff_blast_plus",
    weightGrams: 295,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["rodagem_diaria", "longao", "regenerativo"],
    modelDifferentiator: "Premium comfort Asics — máximo amortecimento para proteção articular.",
  },
  "asics-kayano-31": {
    foamMidsole: "ff_blast_plus",
    weightGrams: 305,
    aggressiveness: "equilibrado",
    stability: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["rodagem_diaria", "longao"],
    modelDifferentiator: "Estabilidade flagship Asics — suporte 4D Guidance para passada controlada.",
  },
  "asics-magic-speed-4": {
    foamMidsole: "ff_turbo",
    hasPlate: true,
    plateType: "composite",
    weightGrams: 245,
    aggressiveness: "agressivo",
    energyReturn: 4,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "intervalado", "meia_maratona"],
    modelDifferentiator: "Speed trainer com placa Asics — treine ritmo com tecnologia de prova acessível.",
  },
  "nike-zoom-fly-6": {
    foamMidsole: "zoomx",
    hasPlate: true,
    plateType: "composite",
    weightGrams: 240,
    aggressiveness: "agressivo",
    energyReturn: 4,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "meia_maratona", "intervalado"],
    modelDifferentiator: "Ponte para super shoes — ZoomX com placa para simular prova sem preço flagship.",
  },
  "nike-pegasus-41": {
    foamMidsole: "react",
    weightGrams: 280,
    aggressiveness: "equilibrado",
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["rodagem_diaria", "longao"],
    modelDifferentiator: "Daily trainer referência Nike — versátil e durável para a maior parte dos treinos.",
  },
  "nike-invincible-3": {
    foamMidsole: "zoomx",
    weightGrams: 310,
    stackHeelMm: 40,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["longao", "regenerativo", "rodagem_diaria"],
    modelDifferentiator: "Max cushion Nike — ZoomX generoso para proteção em alto volume.",
  },
  "nb-1080v14": {
    foamMidsole: "fresh_foam_x",
    weightGrams: 295,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["rodagem_diaria", "longao"],
    modelDifferentiator: "Premium comfort NB — Fresh Foam X macio para easy days e longões.",
  },
  "nb-more-v5": {
    foamMidsole: "fresh_foam_x",
    weightGrams: 320,
    stackHeelMm: 38,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["longao", "regenerativo", "rodagem_diaria"],
    modelDifferentiator: "Max cushion NB — proteção máxima para corredores que priorizam conforto.",
  },
  "saucony-triumph-22": {
    foamMidsole: "pwrrun",
    weightGrams: 300,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["rodagem_diaria", "longao", "regenerativo"],
    modelDifferentiator: "Premium comfort Saucony — PWRRUN generoso para treinos longos e regenerativos.",
  },
  "saucony-endorphin-speed-4": {
    foamMidsole: "pwrrun_pb",
    weightGrams: 235,
    aggressiveness: "agressivo",
    energyReturn: 4,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "intervalado", "meia_maratona"],
    modelDifferentiator: "Speed trainer Saucony — PWRRUN PB responsivo sem placa, ideal para ritmo.",
  },
  "hoka-bondi-9": {
    foamMidsole: "cmeva",
    weightGrams: 295,
    stackHeelMm: 38,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["longao", "regenerativo", "rodagem_diaria"],
    modelDifferentiator: "Max cushion Hoka — meta-rocker suave para proteção articular máxima.",
  },
  "hoka-rocket-x-2": {
    foamMidsole: "peba",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 225,
    aggressiveness: "race_day_extremo",
    energyReturn: 5,
    adaptationLevel: "alta",
    idealUses: ["meia_maratona", "maratona", "prova_curta"],
    modelDifferentiator: "Race day Hoka — PEBA + placa para eficiência energética em prova.",
  },
  "olympikus-corre-grafeno-3": {
    foamMidsole: "peba",
    hasPlate: true,
    plateType: "carbon",
    weightGrams: 220,
    aggressiveness: "race_day_extremo",
    energyReturn: 4,
    adaptationLevel: "alta",
    idealUses: ["meia_maratona", "prova_curta", "treino_ritmo"],
    modelDifferentiator: "Super shoe nacional — placa de carbono e espuma responsiva para prova.",
  },
  "olympikus-corre-supra": {
    foamMidsole: "eva",
    weightGrams: 270,
    aggressiveness: "responsivo",
    energyReturn: 3,
    adaptationLevel: "moderada",
    idealUses: ["treino_ritmo", "intervalado", "rodagem_diaria"],
    modelDifferentiator: "Super trainer Olympikus — resposta acima da média para treinos dinâmicos.",
  },
  "olympikus-corre-max": {
    foamMidsole: "eva_comfort",
    weightGrams: 310,
    aggressiveness: "confortavel",
    softness: 5,
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["longao", "regenerativo", "rodagem_diaria"],
    modelDifferentiator: "Max cushion Olympikus — amortecimento generoso para proteção diária.",
  },
  "olympikus-corre-4": {
    foamMidsole: "eva",
    weightGrams: 275,
    aggressiveness: "equilibrado",
    energyReturn: 3,
    adaptationLevel: "nenhuma",
    idealUses: ["rodagem_diaria", "longao"],
    modelDifferentiator: "Daily trainer Olympikus — versátil e acessível para volume semanal.",
  },
};
