export type FormAnswers = {
  usage: string;
  frequency: string;
  feeling: string;
  price: string;
  weight: string;
  experience: string;
  discomfort: string;
};

export type ShoeTier = "economico" | "intermediario" | "premium" | "performance";

export type Shoe = {
  id: string;
  name: string;
  brand: string;
  price: number;
  tier: ShoeTier;
  hasPlate: boolean;
  comfortLevel: string;
  bestUse: string;
  description: string;
  strengths: string[];
  usage: string[];
  frequency: string[];
  feeling: string[];
  prices: string[];
  weight: string[];
  experience: string[];
  discomfort: string[];
};

export const SHOES: Shoe[] = [
  {
    id: "corre-4",
    name: "Corre 4",
    brand: "Olympikus",
    price: 499,
    tier: "economico",
    hasPlate: false,
    comfortLevel: "Bom nível",
    bestUse: "Caminhar e dar os primeiros passos correndo",
    description:
      "Leve, simples e fácil de usar no dia a dia. Ótimo para quem quer começar sem complicar.",
    strengths: ["Preço acessível", "Leve no pé", "Bom para iniciantes"],
    usage: ["caminhada", "comecar", "academia"],
    frequency: ["1-2", "3-4"],
    feeling: ["macio", "equilibrado"],
    prices: ["400-700"],
    weight: ["ate-70", "70-85"],
    experience: ["nunca", "comecando"],
    discomfort: ["nada", "duro"],
  },
  {
    id: "fila-float-maxx",
    name: "Fila Float Maxx 2",
    brand: "Fila",
    price: 379,
    tier: "economico",
    hasPlate: false,
    comfortLevel: "Macio",
    bestUse: "Caminhada e primeiros treinos curtos",
    description:
      "Conforto macio com preço bem em conta. Ideal para quem está testando a corrida pela primeira vez.",
    strengths: ["Muito acessível", "Sensação macia", "Fácil de usar todo dia"],
    usage: ["caminhada", "comecar"],
    frequency: ["1-2", "3-4"],
    feeling: ["macio"],
    prices: ["ate-400", "400-700"],
    weight: ["ate-70", "70-85"],
    experience: ["nunca", "comecando"],
    discomfort: ["duro", "pe", "nada"],
  },
  {
    id: "olympikus-corre-max",
    name: "Olympikus Corre Max",
    brand: "Olympikus",
    price: 599,
    tier: "economico",
    hasPlate: false,
    comfortLevel: "Muito alto",
    bestUse: "Caminhada e iniciar corrida com conforto",
    description:
      "Espuma generosa que deixa o pé bem acolhido. Perfeito para quem prioriza maciez desde o começo.",
    strengths: ["Muito confortável", "Bom custo-benefício", "Ajuda quando o tênis parece duro"],
    usage: ["caminhada", "comecar", "academia"],
    frequency: ["1-2", "3-4"],
    feeling: ["macio"],
    prices: ["400-700"],
    weight: ["ate-70", "70-85", "acima-85"],
    experience: ["nunca", "comecando"],
    discomfort: ["pe", "joelho", "duro"],
  },
  {
    id: "puma-velocity-nitro",
    name: "Puma Velocity Nitro 2",
    brand: "Puma",
    price: 699,
    tier: "intermediario",
    hasPlate: false,
    comfortLevel: "Equilibrado",
    bestUse: "Treinos leves e corridas regulares",
    description:
      "Leve e confortável, com boa resposta para quem já corre um pouco e quer evoluir sem trocar de tênis cedo.",
    strengths: ["Leve no pé", "Versátil", "Bom para ganhar ritmo"],
    usage: ["comecar", "academia", "frequentes"],
    frequency: ["3-4", "5plus"],
    feeling: ["equilibrado", "leve"],
    prices: ["400-700", "700-1000"],
    weight: ["ate-70", "70-85"],
    experience: ["comecando", "algum-tempo"],
    discomfort: ["nada", "instabilidade"],
  },
  {
    id: "adidas-supernova-rise",
    name: "Adidas Supernova Rise",
    brand: "Adidas",
    price: 799,
    tier: "intermediario",
    hasPlate: false,
    comfortLevel: "Alto e equilibrado",
    bestUse: "Academia, rua ou esteira misturados",
    description:
      "Funciona bem no dia a dia misto — caminhada, corrida leve e academia — sem parecer pesado no pé.",
    strengths: ["Versátil", "Conforto equilibrado", "Bom para rotina variada"],
    usage: ["comecar", "academia", "frequentes", "provas"],
    frequency: ["3-4", "5plus"],
    feeling: ["equilibrado", "macio", "leve"],
    prices: ["700-1000", "400-700"],
    weight: ["ate-70", "70-85"],
    experience: ["comecando", "algum-tempo"],
    discomfort: ["nada", "instabilidade"],
  },
  {
    id: "asics-novablast",
    name: "Asics Novablast 4",
    brand: "Asics",
    price: 899,
    tier: "intermediario",
    hasPlate: false,
    comfortLevel: "Macio com retorno",
    bestUse: "Corridas regulares com sensação leve",
    description:
      "Macio na pisada, mas com um toque de leveza. Bom para quem já corre e quer conforto sem perder agilidade.",
    strengths: ["Conforto e leveza juntos", "Bom para treinos longos", "Sensação moderna"],
    usage: ["frequentes", "academia", "comecar"],
    frequency: ["3-4", "5plus"],
    feeling: ["macio", "equilibrado", "leve"],
    prices: ["700-1000", "400-700"],
    weight: ["70-85", "ate-70", "acima-85"],
    experience: ["algum-tempo", "comecando", "frequente"],
    discomfort: ["pe", "duro", "nada"],
  },
  {
    id: "nike-pegasus",
    name: "Nike Pegasus 41",
    brand: "Nike",
    price: 899,
    tier: "intermediario",
    hasPlate: false,
    comfortLevel: "Equilibrado",
    bestUse: "Treinos variados ao longo da semana",
    description:
      "Um clássico confiável para quase qualquer treino. Equilibrado, previsível e fácil de recomendar para iniciantes que evoluem.",
    strengths: ["Muito versátil", "Confiável", "Funciona em vários tipos de treino"],
    usage: ["comecar", "academia", "frequentes", "provas"],
    frequency: ["3-4", "5plus", "1-2"],
    feeling: ["equilibrado", "leve"],
    prices: ["700-1000", "400-700"],
    weight: ["ate-70", "70-85"],
    experience: ["comecando", "algum-tempo", "frequente"],
    discomfort: ["nada", "instabilidade"],
  },
  {
    id: "on-cloudrunner",
    name: "On Cloudrunner 2",
    brand: "On Running",
    price: 999,
    tier: "intermediario",
    hasPlate: false,
    comfortLevel: "Macio e estável",
    bestUse: "Começar a correr com sensação premium",
    description:
      "Passada suave e estável, com visual moderno. Boa opção para quem quer conforto com cara de tênis premium.",
    strengths: ["Estável no pé", "Conforto suave", "Visual diferenciado"],
    usage: ["comecar", "caminhada", "frequentes"],
    frequency: ["1-2", "3-4", "5plus"],
    feeling: ["macio", "equilibrado"],
    prices: ["700-1000", "1000-2000"],
    weight: ["ate-70", "70-85", "acima-85"],
    experience: ["nunca", "comecando", "algum-tempo"],
    discomfort: ["pe", "joelho", "instabilidade"],
  },
  {
    id: "mizuno-wave-rider",
    name: "Mizuno Wave Rider 27",
    brand: "Mizuno",
    price: 999,
    tier: "intermediario",
    hasPlate: false,
    comfortLevel: "Firme na medida certa",
    bestUse: "Treinos regulares pela semana inteira",
    description:
      "Passada firme e previsível. Indicado para quem já entrou na rotina e quer um tênis confiável.",
    strengths: ["Sensação firme", "Boa durabilidade", "Estável na corrida"],
    usage: ["academia", "frequentes", "comecar", "provas"],
    frequency: ["3-4", "5plus"],
    feeling: ["equilibrado", "leve"],
    prices: ["700-1000", "1000-2000"],
    weight: ["70-85", "ate-70"],
    experience: ["algum-tempo", "comecando", "frequente"],
    discomfort: ["instabilidade", "nada"],
  },
  {
    id: "nike-vomero",
    name: "Nike Vomero 18",
    brand: "Nike",
    price: 1099,
    tier: "premium",
    hasPlate: false,
    comfortLevel: "Muito alto",
    bestUse: "Correr com frequência e muito conforto",
    description:
      "Amortecimento generoso para treinos mais longos. Ideal quando você quer sentir menos cansaço no pé.",
    strengths: ["Conforto acima da média", "Ótimo para volume semanal", "Proteção extra"],
    usage: ["frequentes", "academia", "comecar"],
    frequency: ["3-4", "5plus"],
    feeling: ["macio", "equilibrado"],
    prices: ["700-1000", "1000-2000"],
    weight: ["70-85", "acima-85", "ate-70"],
    experience: ["algum-tempo", "frequente", "comecando"],
    discomfort: ["pe", "joelho", "duro"],
  },
  {
    id: "adidas-boston-12",
    name: "Adidas Adizero Boston 12",
    brand: "Adidas",
    price: 1199,
    tier: "intermediario",
    hasPlate: false,
    comfortLevel: "Leve e responsivo",
    bestUse: "Treinos de ritmo e evolução na corrida",
    description:
      "Mais leve que modelos de conforto puro. Bom para quem já corre e quer sentir mais velocidade nos treinos.",
    strengths: ["Leve e ágil", "Bom para tiros", "Equilíbrio entre conforto e ritmo"],
    usage: ["frequentes", "provas", "academia"],
    frequency: ["3-4", "5plus"],
    feeling: ["leve", "equilibrado"],
    prices: ["700-1000", "1000-2000"],
    weight: ["ate-70", "70-85"],
    experience: ["algum-tempo", "frequente"],
    discomfort: ["nada"],
  },
  {
    id: "nb-1080",
    name: "New Balance Fresh Foam 1080 v13",
    brand: "New Balance",
    price: 1199,
    tier: "premium",
    hasPlate: false,
    comfortLevel: "Muito alto",
    bestUse: "Treinos longos com passada bem suave",
    description:
      "Espuma macia que absorve bem o impacto. Excelente para quem sente desconforto em treinos mais longos.",
    strengths: ["Muito confortável", "Ideal para treinos longos", "Proteção extra"],
    usage: ["comecar", "frequentes", "caminhada"],
    frequency: ["3-4", "5plus", "1-2"],
    feeling: ["macio", "equilibrado"],
    prices: ["700-1000", "1000-2000"],
    weight: ["acima-85", "70-85"],
    experience: ["nunca", "comecando", "algum-tempo"],
    discomfort: ["pe", "joelho", "duro"],
  },
  {
    id: "asics-nimbus",
    name: "Asics Gel-Nimbus 26",
    brand: "Asics",
    price: 1299,
    tier: "premium",
    hasPlate: false,
    comfortLevel: "Dos mais elevados",
    bestUse: "Máximo conforto em cada corrida",
    description:
      "Um dos modelos mais confortáveis da lista. Indicado para quem quer sentir o pé bem protegido o tempo todo.",
    strengths: ["Conforto excepcional", "Ótimo para joelhos sensíveis", "Passada acolhedora"],
    usage: ["caminhada", "comecar", "frequentes"],
    frequency: ["1-2", "3-4", "5plus"],
    feeling: ["macio"],
    prices: ["1000-2000", "700-1000"],
    weight: ["70-85", "acima-85", "ate-70"],
    experience: ["nunca", "comecando", "algum-tempo"],
    discomfort: ["pe", "joelho", "duro"],
  },
  {
    id: "on-cloudmonster",
    name: "On Cloudmonster 2",
    brand: "On Running",
    price: 1299,
    tier: "premium",
    hasPlate: false,
    comfortLevel: "Muito alto",
    bestUse: "Conforto premium no dia a dia",
    description:
      "Amortecimento generoso com visual marcante. Para quem quer conforto máximo sem abrir mão de estilo.",
    strengths: ["Muito macio", "Visual premium", "Conforto duradouro"],
    usage: ["caminhada", "comecar", "frequentes"],
    frequency: ["1-2", "3-4", "5plus"],
    feeling: ["macio", "equilibrado"],
    prices: ["1000-2000", "700-1000"],
    weight: ["70-85", "acima-85"],
    experience: ["nunca", "comecando", "algum-tempo"],
    discomfort: ["pe", "joelho", "duro"],
  },
  {
    id: "fila-racer-carbon",
    name: "Fila Racer Carbon 3",
    brand: "Fila",
    price: 899,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve e rápido",
    bestUse: "Provas e treinos de ritmo forte",
    description:
      "Opção mais acessível com placa para quem quer sentir mais impulso na corrida. Indicado para quem já tem experiência.",
    strengths: ["Placa para mais impulso", "Leve", "Bom custo para performance"],
    usage: ["provas", "frequentes"],
    frequency: ["3-4", "5plus"],
    feeling: ["leve"],
    prices: ["700-1000", "1000-2000"],
    weight: ["ate-70", "70-85"],
    experience: ["algum-tempo", "frequente"],
    discomfort: ["nada"],
  },
  {
    id: "puma-fast-r",
    name: "Puma Fast R Nitro Elite 2",
    brand: "Puma",
    price: 1399,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve e rápido",
    bestUse: "Provas e treinos de ritmo",
    description:
      "Leve, com placa e boa resposta. Para corredores que já treinam com frequência e querem evoluir o ritmo.",
    strengths: ["Placa responsiva", "Muito leve", "Bom para provas"],
    usage: ["provas", "frequentes"],
    frequency: ["3-4", "5plus"],
    feeling: ["leve"],
    prices: ["1000-2000"],
    weight: ["ate-70", "70-85"],
    experience: ["algum-tempo", "frequente"],
    discomfort: ["nada"],
  },
  {
    id: "nike-zoom-fly",
    name: "Nike Zoom Fly 6",
    brand: "Nike",
    price: 1299,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve com impulso",
    bestUse: "Treinos de ritmo e preparação para provas",
    description:
      "Placa e espuma responsiva para treinos mais rápidos. Entrada ideal no mundo dos tênis de performance da Nike.",
    strengths: ["Placa para impulso", "Versátil em treinos rápidos", "Boa transição para provas"],
    usage: ["provas", "frequentes"],
    frequency: ["3-4", "5plus"],
    feeling: ["leve"],
    prices: ["1000-2000"],
    weight: ["ate-70", "70-85"],
    experience: ["algum-tempo", "frequente"],
    discomfort: ["nada"],
  },
  {
    id: "on-cloudboom-echo",
    name: "On Cloudboom Echo 3",
    brand: "On Running",
    price: 1599,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve e rápido",
    bestUse: "Provas e treinos de alta intensidade",
    description:
      "Modelo de performance da On com placa. Para quem busca velocidade e já tem base de corrida consolidada.",
    strengths: ["Placa de performance", "Leveza premium", "Ideal para provas"],
    usage: ["provas", "frequentes"],
    frequency: ["5plus", "3-4"],
    feeling: ["leve"],
    prices: ["1000-2000"],
    weight: ["ate-70", "70-85"],
    experience: ["frequente", "algum-tempo"],
    discomfort: ["nada"],
  },
  {
    id: "asics-metaspeed",
    name: "Asics Metaspeed Sky Paris",
    brand: "Asics",
    price: 1699,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve e rápido",
    bestUse: "Provas e dias de ritmo forte",
    description:
      "Tênis de prova da Asics com placa. Indicado para corredores experientes que querem máximo desempenho.",
    strengths: ["Placa de alta performance", "Muito leve", "Feito para provas"],
    usage: ["provas", "frequentes"],
    frequency: ["5plus", "3-4"],
    feeling: ["leve"],
    prices: ["1000-2000"],
    weight: ["ate-70", "70-85"],
    experience: ["frequente", "algum-tempo"],
    discomfort: ["nada"],
  },
  {
    id: "adidas-adios-pro",
    name: "Adidas Adizero Adios Pro 3",
    brand: "Adidas",
    price: 1899,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve e rápido",
    bestUse: "Provas e performance máxima",
    description:
      "Um dos Adizero mais completos para provas. Placa e espuma de alto desempenho para quem leva a corrida a sério.",
    strengths: ["Placa de elite", "Máximo desempenho", "Referência em provas"],
    usage: ["provas", "frequentes"],
    frequency: ["5plus", "3-4"],
    feeling: ["leve"],
    prices: ["1000-2000", "acima-3000"],
    weight: ["ate-70", "70-85"],
    experience: ["frequente", "algum-tempo"],
    discomfort: ["nada"],
  },
  {
    id: "nike-vaporfly",
    name: "Nike ZoomX Vaporfly 3",
    brand: "Nike",
    price: 1799,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve e rápido",
    bestUse: "Provas e treinos de alta performance",
    description:
      "Referência da Nike para provas. Placa e espuma responsiva para quem quer o máximo de eficiência na corrida.",
    strengths: ["Placa de elite", "Muito eficiente", "Top de linha Nike"],
    usage: ["provas", "frequentes"],
    frequency: ["5plus", "3-4"],
    feeling: ["leve"],
    prices: ["1000-2000", "acima-3000"],
    weight: ["ate-70", "70-85"],
    experience: ["frequente", "algum-tempo"],
    discomfort: ["nada"],
  },
  {
    id: "nike-alphafly",
    name: "Nike Alphafly 3",
    brand: "Nike",
    price: 2299,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve e rápido",
    bestUse: "Provas de alto nível",
    description:
      "O topo da linha Nike para provas. Placa dupla e máxima resposta — para quem busca o melhor desempenho possível.",
    strengths: ["Placa dupla", "Máximo desempenho", "Elite em provas"],
    usage: ["provas", "frequentes"],
    frequency: ["5plus"],
    feeling: ["leve"],
    prices: ["1000-2000", "acima-3000"],
    weight: ["ate-70", "70-85"],
    experience: ["frequente"],
    discomfort: ["nada"],
  },
  {
    id: "adidas-pro-plus",
    name: "Adidas Adizero Prime X Strung",
    brand: "Adidas",
    price: 3499,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve e rápido",
    bestUse: "Provas longas em ritmo forte",
    description:
      "Linha Adizero para quem busca máximo desempenho em corridas maiores — com estrutura de placa pensada para manter ritmo alto.",
    strengths: ["Topo de linha Adidas", "Placa de elite", "Máximo desempenho"],
    usage: ["provas", "frequentes"],
    frequency: ["5plus"],
    feeling: ["leve"],
    prices: ["acima-3000"],
    weight: ["ate-70", "70-85"],
    experience: ["frequente"],
    discomfort: ["nada"],
  },
  {
    id: "on-cloudboom-strike",
    name: "On Cloudboom Strike",
    brand: "On Running",
    price: 3299,
    tier: "performance",
    hasPlate: true,
    comfortLevel: "Leve e rápido",
    bestUse: "Provas de elite",
    description:
      "O modelo mais avançado da On para provas. Placa de elite para corredores que buscam o máximo desempenho.",
    strengths: ["Topo de linha On", "Placa de elite", "Feito para provas"],
    usage: ["provas", "frequentes"],
    frequency: ["5plus"],
    feeling: ["leve"],
    prices: ["acima-3000", "1000-2000"],
    weight: ["ate-70", "70-85"],
    experience: ["frequente"],
    discomfort: ["nada"],
  },
];

export function formatPrice(value: number): string {
  return value.toLocaleString("pt-BR", {
    style: "currency",
    currency: "BRL",
    maximumFractionDigits: 0,
  });
}
